"use client";
import React from "react";
import Link from "next/link";
// import { usePathname } from "next/navigation";

// function ClientLayout({ children }: { children: React.ReactNode }) {
//   const pathname = usePathname();
//   const isActive = pathname.startsWith("/contact");
//   return (
//     <div id="__next">
//       <Link
//         href="/contact"
//         className={isActive ? "text-white" : "text-yellow-600"}
//       >
//         contact
//       </Link>
//       <Link href="/product">product</Link>
//       <Link href="/admin">Admin</Link>
//       {children}
//     </div>
//   );
// }

// export default ClientLayout;

import "../globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Ok",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-red-600">
        <Link href="/product">product</Link>
        <Link href="/admin">Admin</Link>
        {children}
      </body>
    </html>
  );
}
