"use client";
import React from "react";
import Link from "next/link";
import { Button } from "antd";

import "@/styles/globals.css";

export const metadata = {
  title: "linh kien dien tu viet",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="bg-red-500 flex gap-3">
      <Link href="/contact">
        <Button type="primary">contact</Button>
        </Link>
        <Link href="/product">
          <Button type="primary" loading>
            {" "}
            product
          </Button>
        </Link>
        <Link href="/">
          <Button type="primary" >
            Home
          </Button>
        </Link>
        {children}
      </body>
    </html>
  );
}


