import React from "react";
import Link from "next/link";

// function AdminLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <div>
//       <Link href="/admin/contact">contact</Link>
//       <Link href="/admin/product">product</Link>
//       <Link href="/">Home</Link>
//       {/* Nội dung chính */}
//       {children}
//     </div>
//   );
// }

// export default AdminLayout;

import "../globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Ok",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-red-600">
        <Link href="/admin/contact">contact</Link>
        <Link href="/admin/product">product</Link>
        <Link href="/">Home</Link>
        {children}
      </body>
    </html>
  );
}
