'use client';
// import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { Button } from 'antd';
import '@/styles/globals.css';

export const metadata = {
  title: 'linh kien dien tu viet',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [mounted, setMounted] = useState(false);
  // useEffect(() => setMounted(true), []);

  return (
    <html lang="en">
      <body className="flex gap-3 bg-red-500">
        {/* <div style={{ visibility: !mounted ? 'hidden' : 'visible' }}> */}
        <Link href="/contact" >
          <Button type="primary">
              contact
          </Button>
          </Link>
          <Link href="/product">
            <Button type="primary" >
            product
            </Button>
          </Link>
          <Link href="/">
            <Button type="primary" >
            Home
            </Button>
          </Link>
          {children}
        {/* </div> */}
      </body>
    </html>
  );
}


